name: CI Pipeline

on:
    pull_request:
        branches: [main]

jobs:
    lint-and-test:

        runs-on: ubuntu-latest

        steps:  
          - uses: actions/checkout@v4

          - name: Lint Dockerfile
            uses: hadolint/hadolint-action@v3.1.0
            with:
                dockerfile: ./Dockerfile

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: "3.11"

          - name: Install dependencies
            run: pip install -r requirements.txt

          - name: Lint Python
            run: pylint hivebox_app.py

          - name: Run Integration Tests
            run: |
              python hivebox_app.py &
              sleep 5
              pytest test_hivebox_app.py

          - name: Run Terrascan
            uses: tenable/terrascan-action@main
            with:
              iac_type: k8s
              iac_dir: k8s/
              verbose: true

          - name: SonarQube Scan
            uses: sonarsource/sonarqube-scan-action@master
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

          - name: SonarQube Quality Gate check
            uses: sonarsource/sonarqube-quality-gate-action@master
            with:
              pollingTimeoutSec: 600
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    build-and-test:
        runs-on: ubuntu-latest
        needs: lint-and-test
        steps:  
          - uses: actions/checkout@v4
          
          - name: Build Docker Image
            run: docker build -t hivebox:ci .

          - name: Test /version endpoint
            run: |
                docker run -d --name hivebox-ci -p 5000:5000 hivebox:ci
                for i in {1..10}; do
                  if curl -s http://localhost:5000/version | grep -q "0.0.1"; then
                    echo "Endpoint test passed"
                    exit 0
                  fi
                  sleep 2
                done
                echo "Endpoint test failed"
                docker logs hivebox-ci
                exit 1
